### PR TITLE
Undo ClassMethods changes

### PR DESCRIPTION
**Pull request by khwangster**
So.... funny backstory behind this: delayed_job (4.1.3) broke bridges which was only caught by solitude_reports specs (very very many `NoMethodError`s) like so:
 
```
EngagementQualityCalculation#check! ...
     Failure/Error: calculation.check!
     NoMethodError:
       undefined method `find' for Bridges::Creative:Class
```

Now, this PR contains reversing the offending commits. @ajvondrak since you're more familiar with bridges and it's metaprogramming, maybe you can discern why these changes would cause problems. @hsujeremyc just in-case you were curious what was going on.

### CODE REVIEW

**Comment by hsujeremyc** [comment]
lolwat.

So what about facelift...?

edit: nvm, I thought this was a PR for solitude reports

**Comment by ajvondrak** [comment]
Uhhh... I'm confused as to what even is going on. Any better backtraces?
